# Database type
schemaspy.t=pgsql

# Database connection details
schemaspy.host=db
schemaspy.port=15432
schemaspy.db=postgres
schemaspy.u=postgres
schemaspy.p=postgres
schemaspy.s=public

# Output directory for the generated schema diagram
schemaspy.output=/output

# Additional options
schemaspy.imageformat=svg
schemaspy.norows=true
